# Generated by Django 3.1.3 on 2020-11-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('regarding', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=100000000)),
            ],
        ),
    ]
