# Generated by Django 3.1.3 on 2020-12-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
    ]
