# Generated by Django 4.1.2 on 2022-12-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20201214_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('catagory', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=40)),
                ('gender', models.TextField()),
                ('email', models.CharField(max_length=40)),
                ('mobile_number', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
