# Generated by Django 4.1.2 on 2022-12-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogpost',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
