# Generated by Django 4.1.2 on 2023-03-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_delete_blogpost_alter_appointment_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
