# Generated by Django 4.1.2 on 2023-05-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('catagory', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('textarea', models.TextField()),
                ('email', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
